global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'sui-flash-loan-monitor'

scrape_configs:
  # Backend API metrics
  - job_name: 'backend-api'
    static_configs:
      - targets: ['backend:3001']
    metrics_path: '/metrics'
    
  # PostgreSQL metrics
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    
  # Redis metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  # Node exporter for system metrics
  - job_name: 'node'
    static_configs:
      - targets: ['localhost:9100']

# Alerting rules
rule_files:
  - 'alerts.yml'

# Alert manager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: ['localhost:9093']